server:
  port: 8099
spring:
  datasource:
    hikari:
      username: mk
      password: N3fsa4w72prMiSMD
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mk?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8&allowMultiQueries=true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    host: localhost
    port: 6379
  jackson:
    #参数意义：
    #JsonInclude.Include.ALWAYS              默认
    #JsonInclude.Include.NON_DEFAULT     属性为默认值不序列化
    #JsonInclude.Include.NON_EMPTY         属性为 空（””） 或者为 NULL 都不序列化
    #JsonInclude.Include.NON_NULL           属性为NULL   不序列化
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    com.github.xujiaji.mk: debug

mk:
  jwt:
    config:
      redis-jwt-key-prefix: "mk:security:app:jwt:"
  security:
    config:
      enable-api-version: false
      enable-api-request-encrypt: false

      ignores:
        get:
          - "/community/category/all"
          - "/community/topic/all"
          - "/community/article/page"
          - "/community/article/comment/page"
          - "/community/article/comment/details/page"
          - "/front/user/simple/info"
          - "/community/article"
          - "/community/article/own/page"
          - "/community/article/image/page"
          - "/front/app/version"
          - "/diary/community/visible"
        # 需要过滤的 post 请求
        post:
          - "/front/sms/send"
          - "/front/sms/send/modify"
          - "/front/auth/user/sms/send"
          - "/front/auth/user/register"
          - "/front/auth/user/mobile/login"
          - "/front/auth/user/verify/login"
          - "/front/auth/user/forget/password"
          - "/front/auth/user/third/login"
          - "/front/auth/user/mini/wx/login"
          - "/front/auth/user/mini/wx/info/login"
          - "/front/pay/ios"
          - "/front/pay/wx/notify"
          - "/front/pay/ali/notify"
        put:
      password-key: mk-security-password-key-example-app

